Repository aaryan2134/Engineering-Resources, pull requests merged in 2022-10, with the labels that each got.

#96 Typing speed
  Projects/PROJECTS.md
  Projects/Typing_speed_game/README.md
  Projects/Typing_speed_game/speed.py
  Projects/Typing_speed_game/type_speed_img.png
Labels: pending

#111 Modified README.md
  README.md
Labels: hacktoberfest-accepted

#138 added more topics in the links to college subjects and then add it in the contents as well #129
  README.md
Labels: hacktoberfest-accepted

#146 Updated the README.md file with the react query tutorial
  README.md
Labels: invalid
